### ISSUE TITLE
Android MPL 1.5.6_54: NPE in sandbox on review, payments working fine

### ISSUE THREAD

**Issue by Chromdioxyde** [paypal/sdk-packages#69]
Hi there, 
we get a a NullPointerException when we try to review a payment in sandbox mode.
We are using the latest MPL for Android (1.5.6_54) on Android 4.4.2. The odd thing is that this only occurs when trying to review before performing the Payment.
Here is the stacktrace of the error.
```
04-19 10:57:56.088 E/AndroidRuntime( 2352): Process: [...], PID: 2352
04-19 10:57:56.088 E/AndroidRuntime( 2352): java.lang.RuntimeException: Error receiving broadcast Intent { act=APP-80W284485P519543TREPLACE_DIALOG_3 flg=0x10 } in com.paypal.android.MEP.PayPalActivity$2@41fe83c0
[...]
04-19 10:57:56.088 E/AndroidRuntime( 2352):     at dalvik.system.NativeStart.main(Native Method)
04-19 10:57:56.088 E/AndroidRuntime( 2352): Caused by: java.lang.NullPointerException
04-19 10:57:56.088 E/AndroidRuntime( 2352):     at com.paypal.android.MEP.a.c.a(SourceFile:283)
04-19 10:57:56.088 E/AndroidRuntime( 2352):     at com.paypal.android.MEP.a.c.<init>(SourceFile:127)
04-19 10:57:56.088 E/AndroidRuntime( 2352):     at com.paypal.android.MEP.b.g.a(SourceFile:128)
04-19 10:57:56.088 E/AndroidRuntime( 2352):     at com.paypal.android.b.i.<init>(SourceFile:32)
04-19 10:57:56.088 E/AndroidRuntime( 2352):     at com.paypal.android.MEP.b.g.<init>(SourceFile:63)
04-19 10:57:56.088 E/AndroidRuntime( 2352):     at com.paypal.android.MEP.PayPalActivity.a(SourceFile:452)
04-19 10:57:56.088 E/AndroidRuntime( 2352):     at com.paypal.android.MEP.PayPalActivity.b(SourceFile:35)
04-19 10:57:56.088 E/AndroidRuntime( 2352):     at com.paypal.android.MEP.PayPalActivity$2.onReceive(SourceFile:387)
04-19 10:57:56.088 E/AndroidRuntime( 2352):     at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:768)
04-19 10:57:56.088 E/AndroidRuntime( 2352):     ... 9 more
04-19 10:57:56.095 W/ActivityManager( 2079):   Force finishing activity [...]/com.paypal.android.MEP.PayPalActivity
```

Pls tell me if you need more information or have a clue how we can prevent / fix this.

**Comment by elluminati10** [comment]
Paypal latest lib give me error in LIVE Environment "Login failed. Please try again."

i'm stuck
Plz help me


![p](https://cloud.githubusercontent.com/assets/15337099/14910773/1b361a22-0e0e-11e6-97ed-28a2234014a6.png)

**Comment by pp-randy** [comment]
@elluminati10 Are you able to log into www.paypal.com with the same account?

**Comment by pp-randy** [comment]
@Chromdioxyde Are you still having an issue?  I apologize for the delay in follow up.
